# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'parentssoundboard' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for parentssoundboard
  pod 'Google-Mobile-Ads-SDK'
end
